package Site::Model::MyModel;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'MySchema',
    
    connect_info => {
        dsn => 'dbi:mysql:zoogma',
        user => 'root',
        password => 'nick',
    }
);

=head1 NAME

Site::Model::MyModel - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Site>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<MySchema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

Nicholas McCamey

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
